apiVersion: apps/v1 #The API version for Deployment objects
kind: Deployment #The type of object to create
metadata:
  name: order-service #The name of the Deployment
  labels: #A set of labels attached to the Deployment
    app: order-service #This Deployment is labeled with “app=catalog-service.”
spec:
  replicas: 1 #number of pod replicas to deploy
  selector: #Defines the labels used to select the Pods to be scaled
    matchLabels:
      app: order-service
  template: #The template for creating a Pod
    metadata:
      labels: #Labels attached to the Pod object. They should match the ones used as selector
        app: order-service
    spec: #The list of containers in the Pod (one in this case)
      containers:
        - name: order-service #Name of the pod
          image: order-service #image used to run the container, no tag defined so is taking latest implicitly
          imagePullPolicy: IfNotPresent #instructs kubernetes to pull the image from comntainer registry only if not present locally yet
          lifecycle: #Makes Kubernetes wait 5 seconds before sending the SIGTERM signal to the Pod
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9002 #ports exposed by the container
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: POLAR_CATALOG_SERVICE_URI
              value: http://catalog-service
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service
            - name: SPRING_R2DBC_URL
              value: r2dbc:postgresql://polar-postgres/polardb_order
            - name: SPRING_FLYWAY_URL
              value: jdbc:postgresql://polar-postgres/polardb_order